name: Build Test

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Get Commit Hash
        id: get-hash
        run: echo ::set-output name=HASH::$(git rev-parse --short HEAD)
      - run: npm install
      - run: npm install vsce -g
      - run: vsce package -o oi-wiki-vscode-build-${{steps.get-hash.outputs.HASH}}.vsix
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: oi-wiki-vscode-build-${{steps.get-hash.outputs.HASH}}
          path: oi-wiki-vscode-build-${{steps.get-hash.outputs.HASH}}.vsix
